version: "3.9"

services:
  homeassistant:
    container_name: homeassistant-dev
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      # HA Config
      - ./config:/config
      # Dein Add-on Repo direkt ins addons_local mounten
      - ./custom_components/modbus_proxy:/config/addons_local/modbus_proxy
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    network_mode: host
    privileged: true
